// Script: 'jentity.js' , generated by Gamedonia
require (["cscript"], function(mycomm2) {
	
	var my_obj = {name:"pepe"};
	
	var e = mycomm2.toEntityData(my_obj);
	
	gamedonia.data.create("movies", e, {
		
		success: function(res_create) {
			
				log.info(res_create.name);
				response.success();
			},
		error: function(error) {
			
				log.error(error.message);
	            response.error(error.message);
			}	
	});
});